-- MySQL Script generated by MySQL Workbench
-- 03/23/15 17:06:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerce` ;

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ecommerce` ;


-- -----------------------------------------------------
-- Table `ecommerce`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`category` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`product_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`product_list` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`product_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `category_id` INT NULL,
  `inventory_count` INT NULL,
  `qrt_sold` INT NULL,
  `price` FLOAT(5,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`product_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`product_image` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`product_image` (
  `prod_id` INT NOT NULL,
  `line#` INT NULL,
  `imageid` VARCHAR(45) NULL,
  `main` CHAR(1) NULL,
  PRIMARY KEY (`prod_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`order_header`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`order_header` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`order_header` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `date` DATE NULL,
  `bill_first_name` VARCHAR(45) NULL,
  `bill_last_name` VARCHAR(45) NULL,
  `bill_address1` VARCHAR(45) NULL,
  `bill_address2` VARCHAR(45) NULL,
  `bill_city` VARCHAR(45) NULL,
  `bill_state` CHAR(2) NULL,
  `bill_zipcode` INT(5) NULL,
  `ship_first_name` VARCHAR(45) NULL,
  `ship_last_name` VARCHAR(45) NULL,
  `ship_address1` VARCHAR(45) NULL,
  `ship_address2` VARCHAR(45) NULL,
  `ship_city` VARCHAR(45) NULL,
  `ship_state` CHAR(2) NULL,
  `ship_zipcode` INT(5) NULL,
  `card_num` INT(16) NULL,
  `card_sec` INT(3) NULL,
  `card_exp` INT(4) NULL,
  `order_status` VARCHAR(20) NULL,
  `ship_charge` FLOAT(5,2) NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`order_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`order_details` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`order_details` (
  `order_id` INT NOT NULL,
  `item_id` INT NULL,
  `item_qty` INT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
